### ISSUE TITLE
coredns pod is not starting when the k8s cluster implements CIS benckmark rule 5.1.5

### ISSUE THREAD

**Issue by ader1990** [canonical/cluster-api-k8s#107]
Same as https://github.com/canonical/cluster-api-k8s/issues/88, but for coredns.

When k8s-snap is bootstrapped with feature `dns: enabled`, the `coredns` Deployment is using the `default` serviceAccount and the coredns pod is not allowed to mount the kubeconfig volume, thus leading to the `coredns` pod not being able to start. This happens ONLY when the k8s cluster implements CIS benckmark rule 5.1.5 via Kyverno policies.

Coredns container image used:

```
spec:
  containers:
   ...
  image: ghcr.io/canonical/coredns:1.11.3-ck0
  serviceAccount: default
  serviceAccountName: default
  ...
```

Other coredns deployments, for example in the kubeadm cluster api provider, have coredns deployed using a special account called `coredns`, similar to the https://github.com/canonical/cluster-api-k8s/pull/97.

I think this change should be at the level of k8s-snap implementation, please let me know if I should move the issue to that repository.

Thanks.
