### ISSUE TITLE
Add support for CP rollout strategy configuration

### ISSUE THREAD

**Issue by ader1990** [canonical/cluster-api-k8s#116]
Currently, there is no configuration option for the rollout strategy regarding CK8SControlPlane.

Would be great to have a way to configure it in the future, similar to how kubeadm or rke2 cluster api providers implement it - https://github.com/rancher/cluster-api-provider-rke2/blob/main/controlplane/api/v1beta1/rke2controlplane_types.go#L99.

Example spec:

```
spec:
  strategy:
      rollingUpdate:
        maxSurge: 0
      type: RollingUpdate
```

Thanks.
