### ISSUE TITLE
controlplane-controller:v0.2.0 OOM killed

### ISSUE THREAD

**Issue by ader1990** [canonical/cluster-api-k8s#89]
Hello,

The controlplane-controller pod container is crashing with OOM killed every time I try to start it and start reconciling one cluster control plane:

```
  containerStatuses:
  - containerID: containerd://33fd072523585dcb8de1e6d42007fb17b4e64581c7b436cf45ce8caa7ce12daa
    image: ghcr.io/canonical/cluster-api-k8s/controlplane-controller:v0.2.0
    imageID: ghcr.io/canonical/cluster-api-k8s/controlplane-controller@sha256:459f35dc1c9aaa57e08369e6dcca55d10565211c6b29039cb745b97bcbb7c1e0
    lastState:
      terminated:
        containerID: containerd://33fd072523585dcb8de1e6d42007fb17b4e64581c7b436cf45ce8caa7ce12daa
        exitCode: 137
        finishedAt: "2025-01-14T08:41:38Z"
        reason: OOMKilled
        startedAt: "2025-01-14T08:41:17Z"

```

Definition of the container from the release yaml file:

```
        image: ghcr.io/canonical/cluster-api-k8s/controlplane-controller:v0.2.0
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
```

I see that the `resources.limits.memory=30Mi`, which is most likely not enough.
